project_id = "zciovdjrasfitgpisnng"

[functions.weather-data]
verify_jwt = true

[functions.configure-reports]
verify_jwt = true

[functions.send-production-report]
verify_jwt = true

[functions.process-alerts]
verify_jwt = true

[functions.get-user-metrics]
verify_jwt = true

[functions.process-spreadsheet]
verify_jwt = false

[functions.extract-pdf-data]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false
